CREATE TABLE IF NOT EXISTS dim_stock (
    stock_code VARCHAR(20) PRIMARY KEY,
    stock_name VARCHAR(100) NOT NULL,
    exchange_code VARCHAR(10),
    industry_name VARCHAR(100),
    is_active TINYINT DEFAULT 1,
    listing_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fact_daily_bar (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    stock_code VARCHAR(20) NOT NULL,
    trade_date DATE NOT NULL,
    open DECIMAL(10,3),
    high DECIMAL(10,3),
    low DECIMAL(10,3),
    close DECIMAL(10,3),
    volume BIGINT,
    amount DECIMAL(20,3),
    change_pct DECIMAL(10,3),
    turnover_rate DECIMAL(10,3),
    amplitude DECIMAL(10,3),
    pre_close DECIMAL(10,3),
    ma5 DECIMAL(10,3),
    ma10 DECIMAL(10,3),
    ma20 DECIMAL(10,3),
    ma30 DECIMAL(10,3),
    ma60 DECIMAL(10,3),
    ma120 DECIMAL(10,3),
    ma250 DECIMAL(10,3),
    volume_ratio DECIMAL(10,3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_stock_date (stock_code, trade_date),
    INDEX idx_trade_date (trade_date),
    INDEX idx_stock_code (stock_code)
);

CREATE TABLE IF NOT EXISTS fact_financial (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    stock_code VARCHAR(20) NOT NULL,
    report_date DATE NOT NULL,
    report_type VARCHAR(20),
    revenue DECIMAL(20,3),
    revenue_yoy DECIMAL(10,3),
    net_profit DECIMAL(20,3),
    net_profit_yoy DECIMAL(10,3),
    roe DECIMAL(10,3),
    gross_margin DECIMAL(10,3),
    net_margin DECIMAL(10,3),
    eps DECIMAL(10,3),
    bps DECIMAL(10,3),
    pe_ratio DECIMAL(10,3),
    pb_ratio DECIMAL(10,3),
    ps_ratio DECIMAL(10,3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_stock_report (stock_code, report_date, report_type),
    INDEX idx_report_date (report_date),
    INDEX idx_stock_code (stock_code)
);